// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: COCDemo.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GrpcCOCDemo {
  public static partial class COCDemo
  {
    static readonly string __ServiceName = "grpc.COCDemo";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectListRequest> __Marshaller_grpc_GetObjectListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectListResponse> __Marshaller_grpc_GetObjectListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetSkillListRequest> __Marshaller_grpc_GetSkillListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetSkillListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetSkillListResponse> __Marshaller_grpc_GetSkillListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetSkillListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.CheckFeasibleRequest> __Marshaller_grpc_CheckFeasibleRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.CheckFeasibleRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.CheckFeasibleResponse> __Marshaller_grpc_CheckFeasibleResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.CheckFeasibleResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetSkillUsedRequest> __Marshaller_grpc_GetSkillUsedRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetSkillUsedRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetSkillUsedResponse> __Marshaller_grpc_GetSkillUsedResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetSkillUsedResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectReplyRequest> __Marshaller_grpc_GetObjectReplyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectReplyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectReplyResponse> __Marshaller_grpc_GetObjectReplyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectReplyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectActionRequest> __Marshaller_grpc_GetObjectActionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectActionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GrpcCOCDemo.GetObjectActionResponse> __Marshaller_grpc_GetObjectActionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GrpcCOCDemo.GetObjectActionResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.GetObjectListRequest, global::GrpcCOCDemo.GetObjectListResponse> __Method_GetObjectList = new grpc::Method<global::GrpcCOCDemo.GetObjectListRequest, global::GrpcCOCDemo.GetObjectListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetObjectList",
        __Marshaller_grpc_GetObjectListRequest,
        __Marshaller_grpc_GetObjectListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.GetSkillListRequest, global::GrpcCOCDemo.GetSkillListResponse> __Method_GetSkillList = new grpc::Method<global::GrpcCOCDemo.GetSkillListRequest, global::GrpcCOCDemo.GetSkillListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSkillList",
        __Marshaller_grpc_GetSkillListRequest,
        __Marshaller_grpc_GetSkillListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.CheckFeasibleRequest, global::GrpcCOCDemo.CheckFeasibleResponse> __Method_CheckFeasible = new grpc::Method<global::GrpcCOCDemo.CheckFeasibleRequest, global::GrpcCOCDemo.CheckFeasibleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckFeasible",
        __Marshaller_grpc_CheckFeasibleRequest,
        __Marshaller_grpc_CheckFeasibleResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.GetSkillUsedRequest, global::GrpcCOCDemo.GetSkillUsedResponse> __Method_GetSkillUsed = new grpc::Method<global::GrpcCOCDemo.GetSkillUsedRequest, global::GrpcCOCDemo.GetSkillUsedResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSkillUsed",
        __Marshaller_grpc_GetSkillUsedRequest,
        __Marshaller_grpc_GetSkillUsedResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.GetObjectReplyRequest, global::GrpcCOCDemo.GetObjectReplyResponse> __Method_GetObjectReply = new grpc::Method<global::GrpcCOCDemo.GetObjectReplyRequest, global::GrpcCOCDemo.GetObjectReplyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetObjectReply",
        __Marshaller_grpc_GetObjectReplyRequest,
        __Marshaller_grpc_GetObjectReplyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GrpcCOCDemo.GetObjectActionRequest, global::GrpcCOCDemo.GetObjectActionResponse> __Method_GetObjectAction = new grpc::Method<global::GrpcCOCDemo.GetObjectActionRequest, global::GrpcCOCDemo.GetObjectActionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetObjectAction",
        __Marshaller_grpc_GetObjectActionRequest,
        __Marshaller_grpc_GetObjectActionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GrpcCOCDemo.COCDemoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of COCDemo</summary>
    [grpc::BindServiceMethod(typeof(COCDemo), "BindService")]
    public abstract partial class COCDemoBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.GetObjectListResponse> GetObjectList(global::GrpcCOCDemo.GetObjectListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.GetSkillListResponse> GetSkillList(global::GrpcCOCDemo.GetSkillListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.CheckFeasibleResponse> CheckFeasible(global::GrpcCOCDemo.CheckFeasibleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.GetSkillUsedResponse> GetSkillUsed(global::GrpcCOCDemo.GetSkillUsedRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.GetObjectReplyResponse> GetObjectReply(global::GrpcCOCDemo.GetObjectReplyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GrpcCOCDemo.GetObjectActionResponse> GetObjectAction(global::GrpcCOCDemo.GetObjectActionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for COCDemo</summary>
    public partial class COCDemoClient : grpc::ClientBase<COCDemoClient>
    {
      /// <summary>Creates a new client for COCDemo</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public COCDemoClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for COCDemo that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public COCDemoClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected COCDemoClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected COCDemoClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectListResponse GetObjectList(global::GrpcCOCDemo.GetObjectListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectListResponse GetObjectList(global::GrpcCOCDemo.GetObjectListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetObjectList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectListResponse> GetObjectListAsync(global::GrpcCOCDemo.GetObjectListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectListResponse> GetObjectListAsync(global::GrpcCOCDemo.GetObjectListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetObjectList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetSkillListResponse GetSkillList(global::GrpcCOCDemo.GetSkillListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkillList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetSkillListResponse GetSkillList(global::GrpcCOCDemo.GetSkillListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSkillList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetSkillListResponse> GetSkillListAsync(global::GrpcCOCDemo.GetSkillListRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkillListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetSkillListResponse> GetSkillListAsync(global::GrpcCOCDemo.GetSkillListRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSkillList, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.CheckFeasibleResponse CheckFeasible(global::GrpcCOCDemo.CheckFeasibleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckFeasible(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.CheckFeasibleResponse CheckFeasible(global::GrpcCOCDemo.CheckFeasibleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckFeasible, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.CheckFeasibleResponse> CheckFeasibleAsync(global::GrpcCOCDemo.CheckFeasibleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckFeasibleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.CheckFeasibleResponse> CheckFeasibleAsync(global::GrpcCOCDemo.CheckFeasibleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckFeasible, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetSkillUsedResponse GetSkillUsed(global::GrpcCOCDemo.GetSkillUsedRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkillUsed(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetSkillUsedResponse GetSkillUsed(global::GrpcCOCDemo.GetSkillUsedRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSkillUsed, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetSkillUsedResponse> GetSkillUsedAsync(global::GrpcCOCDemo.GetSkillUsedRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSkillUsedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetSkillUsedResponse> GetSkillUsedAsync(global::GrpcCOCDemo.GetSkillUsedRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSkillUsed, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectReplyResponse GetObjectReply(global::GrpcCOCDemo.GetObjectReplyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectReply(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectReplyResponse GetObjectReply(global::GrpcCOCDemo.GetObjectReplyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetObjectReply, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectReplyResponse> GetObjectReplyAsync(global::GrpcCOCDemo.GetObjectReplyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectReplyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectReplyResponse> GetObjectReplyAsync(global::GrpcCOCDemo.GetObjectReplyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetObjectReply, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectActionResponse GetObjectAction(global::GrpcCOCDemo.GetObjectActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectAction(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::GrpcCOCDemo.GetObjectActionResponse GetObjectAction(global::GrpcCOCDemo.GetObjectActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetObjectAction, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectActionResponse> GetObjectActionAsync(global::GrpcCOCDemo.GetObjectActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetObjectActionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::GrpcCOCDemo.GetObjectActionResponse> GetObjectActionAsync(global::GrpcCOCDemo.GetObjectActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetObjectAction, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override COCDemoClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new COCDemoClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(COCDemoBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetObjectList, serviceImpl.GetObjectList)
          .AddMethod(__Method_GetSkillList, serviceImpl.GetSkillList)
          .AddMethod(__Method_CheckFeasible, serviceImpl.CheckFeasible)
          .AddMethod(__Method_GetSkillUsed, serviceImpl.GetSkillUsed)
          .AddMethod(__Method_GetObjectReply, serviceImpl.GetObjectReply)
          .AddMethod(__Method_GetObjectAction, serviceImpl.GetObjectAction).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, COCDemoBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetObjectList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.GetObjectListRequest, global::GrpcCOCDemo.GetObjectListResponse>(serviceImpl.GetObjectList));
      serviceBinder.AddMethod(__Method_GetSkillList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.GetSkillListRequest, global::GrpcCOCDemo.GetSkillListResponse>(serviceImpl.GetSkillList));
      serviceBinder.AddMethod(__Method_CheckFeasible, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.CheckFeasibleRequest, global::GrpcCOCDemo.CheckFeasibleResponse>(serviceImpl.CheckFeasible));
      serviceBinder.AddMethod(__Method_GetSkillUsed, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.GetSkillUsedRequest, global::GrpcCOCDemo.GetSkillUsedResponse>(serviceImpl.GetSkillUsed));
      serviceBinder.AddMethod(__Method_GetObjectReply, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.GetObjectReplyRequest, global::GrpcCOCDemo.GetObjectReplyResponse>(serviceImpl.GetObjectReply));
      serviceBinder.AddMethod(__Method_GetObjectAction, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GrpcCOCDemo.GetObjectActionRequest, global::GrpcCOCDemo.GetObjectActionResponse>(serviceImpl.GetObjectAction));
    }

  }
}
#endregion
